---
title: Chris
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    excerpt_separator: "<!--more-->"
    layout: post
markdown: kramdown
highlighter: rouge
tagline: A Personal Blog
description: This is my website.
url: https://chrisfnicholson.com
baseurl: ''
author:
  name: Chris
  url: https://twitter.com/chrisfnicholson
paginate: 5
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- Makefile
- README.md
- ".gitignore"
permalink: "/:year/:month/:day/:title.html"
sidebar_home_link: true
page_gen:
- data: recipes
  template: recipe
  name: name
  dir: recipes
  extension: html
disqus:
  shortname: hydeout
google_analytics: UA-100461102-1
